# bujo-thinking
my thinking of bujo and bujo-mode
** 分享|用bujo统一管理任务笔记和思考
     在遇到bujo之前，我用过很多的方法、app来管理自己的时间笔记日记，比如：evernote，日记本，org-mode，omnifocus，各种小的todo app.....毫无疑问，这些都是很优秀的软件与管理方式。但是零零碎碎的分散开来让我一直不满意，我一直希望有一种方法能够将“时间管理”，“笔记灵感”，“日记反思”，“追踪记录”这些需求统一融合起来。

     一个偶然机会，在kindle封面的书籍推荐看到了《子弹笔记》，即bujo。带着好奇心了解了一下，猛的的发现这就是我一直以来所寻找的东西呀！就像当初遇到emacs一样，我对bujo的热爱到了痴迷的程度，花了几天时间，一口气读完了这本书。读完后更加赞叹这个笔记术的精妙，其时间管理上巧妙的闭环更是让我激动不已！下面进入正题，简单介绍bujo的原理，希望对大家有所帮助。

     bujo使用子弹短句表示任务、笔记、事件，用不同的符号表示类型与状态。子弹短句由特殊符号和内容组成。
**** 重要概念与实践
     1. 子弹短句分为三类：任务，事件，笔记，分别用"●", "○", "─"表示。
     2. 任务状态有5种：待做，迁移，计划，完成，舍弃，分别用"●", ">", "<", "×", "+task+"表示。
     3. 其他符号：★表示重要，!表示有灵感。
     4. 集子：一系列子弹短句的集合就是一个集子。bujo核心的集子有“未来记录”，“月度记录”，“每日记录”，当然你也可以制作个性化的集子。
     5. 核心集子的使用：
       1) 未来记录：记录将来计划要做的任务。
       2) 月度记录：分四列，第一列为日期；第二列为事件列，记录当月发生的事件；第三列为月度任务列，记录当月待做任务；最后一列为日历清单，记录本月特定日期要做的任务。
       3) 每日记录：记录每天待做的task(●)，发生的重要的事情(○)，以及笔记(─)，最后一项是日反思。
     6. 状态改变：任务完成后，将"●"改为"×"; 当日任务没有完成，将"●"改为">",并在第二天任务规划时重新抄写被推迟的任务; 任务计划在将来完成，用"<"表示；任务被推迟的次数太多，考察任务的重要性与必要性，可以舍弃则在任务上画横杠 +task+ 。许多任务有相关性，决定迁移到专门的集子中，也用">"。
     7. 任务迁移：这是bujo进行任务管理的核心所在！每个月的第一天进行月度迁移：考察未来记录中的待做任务，把可能在本月完成的任务抄到月度记录中，并在未来记录做">"标记；在每日规划的时候考察月度记录，把需要在当天完成的任务迁移到今日记录中，并在月度记录中标记">"。以此类推，年度迁移即考察未来记录并做迁移。
     8. 个性集子：个性集子形式多样，可以用来跟踪记录，规划大的项目，反思自身习惯，做专项笔记......

**** 我的思考与理解
     1. 我把待办任务分为四类：长期无截止日期：习惯(跑步，阅读...)；长期有截止日期：项目(毕设，开发bujo-mode...)；在特定时间做：约定(会议...)；短期要做的小事：待办小事(理发，买衣服...)
     2. 针对四类不同的任务类型，bujo用不同的处理方式。“习惯”记录在未来记录中，状态始终为“●”，除了年度迁移，其余情况状态永远不变。“项目”建议建立单独的个性化集子，在该集子中进行任务分解。“约定”记录在月度记录的日历清单(第四列)中。待办小事正常记录在每日记录或月度记录中。
     3. 每日记录应当考察三个方面：月度记录，昨日记录中的“>”和脑中所想。日规划，夜反思。夜反思要考察一天任务完成情况，记录的笔记灵感，以及重要事件。
     4. bujo的闭环系统让你不会漏掉脑袋中产生的任何想法，这正是任务迁移精妙的地方。

**** bujo与emacs的结合
     bujo是一套很好的规划与记录的手帐笔记术，配合手帐的记录方式可以让记录的过程充满乐趣。随着一页页的记录，成就感也会让人更容易坚持。但是作为一个“手癌患者”，实在不适合做这些精细活，于是便思考借用bujo的思想与emacs相结合(如果使用笔记本记录bujo，它的索引系统的设计也是值得好好阐述的，这里就不详细展开了)。

     看完书后我的脑海中就逐步构建起来了一系列bujo在emacs中的呈现方式，有几天的时间里都在脑海中反复打磨，兴奋不已。我觉得如果能够实现，是可以当作org capture和org agenda的另一种替代方案的。只不过bujo的原理需要一定的学习成本，但掌握后之后会收益很多。

     由于我是elisp的初学者，又正值大四毕业阶段，时间和能力都有限。所以短时间内无法实现这个"bujo-mode", 如果有感兴趣的伙伴，欢迎尝试！

     附：[[https://bulletjournal.com][bujo官网]], [[https://github.com/Kinneyzhang/bujo-thinking][bujo-mode设计思路]]

** bujo-mode设计思路(初稿)
*** bujo-agenda
    * F:bujo-agenda-future-view 未来记录(Future Log)
    * M:bujo-agenda-month-view 月度记录(Monthly Log)
    * D:bujo-agenda-ady-view 每日记录(Daily Log)
    * a:bujo-agenda-task-abort
    * d:bujo-agenda-task-done => × (done)
    * m:bujo-agenda-task-migrated => > (migrated)
      - task状态变为“>”
      - 选择要迁移到的日期或新集子
   * s:bujo-agenda-task-sheculed => < (schedule)
      - task状态变为“<”
      - 在未来记录中添加该task
   * n:bujo-agenda-next-line
      - p:bujo-agenda-previous-line
      - f:bujo-agenda-later
      - b:bujo-agenda-earlier
      - .:bujo-agenda-goto-today
      - j:bujo-agenda-goto-date
      - r:bujo-agenda-refresh
      - Tab bujo-agenda-goto
      - q:bujo-agenda-quit
      - x:bujo-agenda-exit

*** bujo-agenda-file
     * 自动生成特定格式的bujo.org
     * 解析bujo.org, 实现bujo.org和bujo agenda的双向动态更新

*** bujo-select
     * keybinding: C-c b
       | Select a capture template |
       |---------------------------|
       | [t]  Task                 |
       | [e]  Event                |
       | [n]  Note                 |

    * key-point
      - bujo-select选择t的时候将窗口分成左右两列，左边默认为bujo-agenda，显示昨天的记录，方便迁移
      - 只有task状态可变。自动对task的状态进行排序，依次为：todo-migrated-scheduled-done-abort，r刷新
      - bujo-agenda打开的默认展示为当天的Daily Log，分为三类：task, event, note
       - n, p上下移动；task可改变状态：t(todo), m(migrate), s(scheduled), d(done), a(abort)
       - f, b向前向后切换记录，“.”回到当天记录，j调用日历跳转到指定日期的日记录
      - 按键M显示月度记录页，分四列
       | Date  | Event    | Monthly Task | Calendar Task |
       |-------+----------+--------------+---------------|
       | 1 Wes | ○ thing1 | ● task1      |               |
       | 2 Thu | ○ thing2 | ● task2      |               |
       | 3 Fri | ○ thing3 |              | ● task11      |
       | 4 Sta |          |              |               |
       | 5 Sun |          |              | ● task22      |
       | ..... | .....    | .....        |               |
     - 同理n,p,f,b,.,j,t,m,s,d,a
     - 按键F显示未来记录, 简单的task列表
